### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by schoettl** [mpkasp/django-bom#5]
Hi, I'm just trying to install.

I think the starting from scratch install guide should mention that dependencies from `requirements.txt` should be installed with `pip install -r requirements.txt`. Instead of just `pip install django`

**Comment by mpkasp** [comment]
The intent was to try to make django-bom a reusable application that can be installed via pypi and added to a larger django project. At the same time allow it to work as a standalone django project. The readme is set up to allow a user to add the app to their larger django project, in which they wouldn't easily be able to do a `pip install -r requirements.txt`. I see what you're saying and will add a readme section for those that want to install django-bom as a standalone django project.

Otherwise I also will update the setup.py to include some new dependencies that I've added recently.
